#ifndef INCLUDE_MEMORYMAP_H_
#define INCLUDE_MEMORYMAP_H_

#define MEGABYTE		0x100000

/* sizes */
#define KERNEL_MAX_SIZE		(2 * MEGABYTE)
#define SVC_STACK_SIZE		0x1000
#define IRQ_STACK_SIZE		0x1000
#define FIQ_STACK_SIZE		0x1000
#define ABT_STACK_SIZE		0x1000
#define UND_STACK_SIZE		0x1000
#define USRSYS_STACK_SIZE	0x2000

/* memory map */
#define KERNEL_START		0x8000
#define KERNEL_END		(KERNEL_START + KERNEL_MAX_SIZE)

#define SVC_STACK_TOP		(KERNEL_END + SVC_STACK_SIZE)
#define IRQ_STACK_TOP		(SVC_STACK_TOP + IRQ_STACK_SIZE)
#define FIQ_STACK_TOP		(IRQ_STACK_TOP + FIQ_STACK_SIZE)
#define ABT_STACK_TOP		(FIQ_STACK_TOP + ABT_STACK_SIZE)
#define UND_STACK_TOP		(ABT_STACK_TOP + UND_STACK_SIZE)
#define USRSYS_STACK_TOP	(UND_STACK_TOP + USRSYS_STACK_SIZE)

#define FREE_MEM		USRSYS_STACK_TOP

#endif /* INCLUDE_MEMORYMAP_H_ */
